### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, boolean given in globie-vimeo-sucker.php on line 61

### ISSUE THREAD

**Issue by varffs** [interglobalvision/globie-vimeo-sucker#8]

**Comment by mixcas** [comment]
I encounter this when i was developing, it happened when the settings were all empty but fixed it… i thought.
How is it happening to you?

**Comment by varffs** [comment]
Can u perhaps comment and explain the code in that section. I dont really understand what is going on there, why u are using that php function and what `$options` is?

(P.s. There is this really great local env called mamp check it out)

Wp is latest will check php in a bit

**Comment by mixcas** [comment]
$options its the options saved by the settings page. 
get_options() .-
>A safe way of getting values for a named option from the options database table. If the desired option does not exist, or no value is associated with it, FALSE will be returned.

its a mixed value so u gotta check it first.

Anyway, I'm gonna rewrite this part cuz theres no need to check agains each post type available.

Still, I can't reproduce this bug.

When opening bug issues please be more descriptive. We all hate "it doesn't work" bug reports, right?

ps. MAMP? take a [rare candy](http://pokemon.wikia.com/wiki/Rare_Candy) and level up man

**Comment by varffs** [comment]
closing this as sucker seems to be working fine atm
